version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: chocolate_admin
      POSTGRES_PASSWORD: 123Malak
      POSTGRES_DB: chocolate_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/photos:/app/photos
    healthcheck:  # Properly formatted healthcheck
      test: ["CMD-SHELL", "pg_isready -U chocolate_admin -d chocolate_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: "5432"
      DB_USER: chocolate_admin
      DB_PASSWORD: 123Malak
      DB_NAME: chocolate_db
    volumes:
      - ./backend/photos:/app/photos

  frontend:
    build: ./frontend
    ports:
      - "3001:3001"
    depends_on:
      - backend

volumes:
  postgres_data: